# Generated by Django 3.0.8 on 2020-09-09 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=50, verbose_name='Book name')),
                ('book_author', models.CharField(max_length=30, verbose_name='Book author')),
                ('date_published', models.DateField()),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('dean', models.CharField(max_length=30)),
                ('course_name', models.CharField(max_length=150, verbose_name='Course name')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('g_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_level', models.PositiveSmallIntegerField(verbose_name='Course level')),
                ('g_name', models.CharField(max_length=30, verbose_name='Group name')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(null=True)),
                ('course_id', models.ManyToManyField(to='profileApp.Courses')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=20, verbose_name='Role name')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=20, verbose_name='Subject namem')),
                ('room_number', models.PositiveSmallIntegerField(verbose_name='Room number')),
                ('sub_book_id', models.ManyToManyField(to='profileApp.Books')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='UserExtend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thirdname', models.CharField(blank=True, max_length=30, null=True, verbose_name='Thirdname')),
                ('date_of_birth', models.DateField(verbose_name='Date of birth')),
                ('phone_number', models.CharField(blank=True, default='+998', max_length=50, null=True, verbose_name='Phone number')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='account_photo/', verbose_name='Upload photo')),
                ('region', models.CharField(help_text="Enter user's region (Fergana, Tashkent viloyat, Samarkand)", max_length=30, verbose_name='Region of a Country')),
                ('city', models.CharField(help_text="Enter user's city (Fergana, Tashkent, Samarkand)", max_length=30, verbose_name='City')),
                ('passport_series', models.CharField(help_text='two letters', max_length=5, verbose_name='Passport series')),
                ('passport_number', models.CharField(max_length=10, verbose_name='Passport number')),
                ('home_address', models.CharField(max_length=70, verbose_name='Home address')),
                ('rating', models.PositiveSmallIntegerField(default=0, verbose_name='Rating')),
                ('url', models.SlugField(default='url', unique=True)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileApp.Roles')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ManyToManyField(to='profileApp.Subjects')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileApp.UserExtend', to_field='user_id')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'db_table': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileApp.Groups')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileApp.UserExtend', to_field='user_id')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
