# Generated by Django 3.1.1 on 2020-10-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0002_books_courses_groups_profile_roles_student_subjects_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.CharField(default='Tashkent', help_text="Enter user's region (Fergana, Tashkent viloyat, Samarkand)", max_length=30, verbose_name='Region of a Country'),
        ),
    ]
