# Generated by Django 3.0.8 on 2020-09-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0002_auto_20200909_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='role',
            field=models.ManyToManyField(to='profileApp.Roles'),
        ),
        migrations.AlterField(
            model_name='userextend',
            name='url',
            field=models.SlugField(default='<django.db.models.fields.related.OneToOneField>', unique=True),
        ),
    ]
