# Generated by Django 3.1.1 on 2020-10-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0003_auto_20201007_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Tashkent', help_text="Enter user's city (Fergana, Tashkent, Samarkand)", max_length=30, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passport_series',
            field=models.CharField(default='aa', help_text='two letters', max_length=5, verbose_name='Passport series'),
        ),
    ]
