# Generated by Django 3.0.8 on 2020-09-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0004_auto_20200909_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='url',
            field=models.SlugField(default='default', unique=True),
        ),
    ]
