# Generated by Django 3.0.8 on 2020-09-09 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0005_auto_20200909_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextend',
            name='role',
        ),
        migrations.AddField(
            model_name='userextend',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profileApp.Roles'),
        ),
    ]
