# Generated by Django 3.1.1 on 2020-10-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0005_courses_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='url',
            field=models.SlugField(null=True),
        ),
    ]
