# Generated by Django 3.0.8 on 2020-09-09 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0006_auto_20200909_1100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserExtend',
        ),
    ]
