# Generated by Django 3.0.8 on 2020-09-09 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profileApp', '0007_delete_userextend'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thirdname', models.CharField(blank=True, max_length=30, null=True, verbose_name='Thirdname')),
                ('date_of_birth', models.DateField(verbose_name='Date of birth')),
                ('phone_number', models.CharField(blank=True, default='+998', max_length=50, null=True, verbose_name='Phone number')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='account_photo/', verbose_name='Upload photo')),
                ('region', models.CharField(help_text="Enter user's region (Fergana, Tashkent viloyat, Samarkand)", max_length=30, verbose_name='Region of a Country')),
                ('city', models.CharField(help_text="Enter user's city (Fergana, Tashkent, Samarkand)", max_length=30, verbose_name='City')),
                ('passport_series', models.CharField(help_text='two letters', max_length=5, verbose_name='Passport series')),
                ('passport_number', models.CharField(max_length=10, verbose_name='Passport number')),
                ('home_address', models.CharField(max_length=70, verbose_name='Home address')),
                ('rating', models.PositiveSmallIntegerField(default=0, verbose_name='Rating')),
                ('url', models.SlugField(default='default', unique=True)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profileApp.Roles')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
