# Generated by Django 3.0.8 on 2020-09-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0008_userextend'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='out_date',
            field=models.DateField(null=True, verbose_name='Out date '),
        ),
        migrations.AddField(
            model_name='userextend',
            name='reg_date',
            field=models.DateField(null=True, verbose_name='Date of registration'),
        ),
        migrations.AlterField(
            model_name='userextend',
            name='url',
            field=models.SlugField(default='None_id', unique=True),
        ),
    ]
