# Generated by Django 3.0.8 on 2020-09-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0009_auto_20200911_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userextend',
            name='url',
            field=models.SlugField(default=models.AutoField(primary_key=True, serialize=False), unique=True),
        ),
    ]
