# Generated by Django 3.0.8 on 2020-09-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0010_auto_20200911_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='url',
            field=models.SlugField(default='<django.db.models.fields.AutoField>', unique=True),
        ),
    ]
