# Generated by Django 3.0.8 on 2020-09-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0013_auto_20200911_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='url',
            field=models.SlugField(default='none', unique=True),
        ),
    ]
