# Generated by Django 3.1.1 on 2020-09-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0014_auto_20200911_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='userextend',
            name='url',
            field=models.SlugField(default='none    ', unique=True),
        ),
    ]
